---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rekor
  namespace: rekor-system
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: rekor-system
  name: rekor
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      serviceAccountName: rekor
      containers:
      - name: rekor
        image: gcr.io/projectsigstore/rekor-server:v1.3.6@sha256:1237f29e2105d7f5451bbe15a3aca8677ddd1bb80620ca2fd06f74262437cf51
        ports:
        - containerPort: 3000
        args: [
          "serve",
          "--trillian_log_server.address=log-server.trillian-system.svc",
          "--trillian_log_server.port=80",
          "--rekor_server.address=0.0.0.0",
          "--redis_server.address=redis.rekor-system.svc",
          "--redis_server.port=6379",
          "--enable_retrieve_api=true",
          "--trillian_log_server.tlog_id=$(TREE_ID)",
          "--log_type=prod",
          "--rekor_server.signer=/var/run/rekor-secrets/signing-secret",
          "--rekor_server.signer-passwd=$(SECRET_SIGNING_PWD)",
          "--enable_attestation_storage=true",
          "--attestation_storage_bucket=file:///tmp/",
          "--search_index.mysql.conn_max_idletime=300s",
          "--search_index.mysql.conn_max_lifetime=2100s",
          "--search_index.mysql.max_open_connections=300",
          "--search_index.mysql.max_idle_connections=100",
#          "--rekor_server.timestamp_chain=$(TIMESTAMP_CHAIN)"
        ]
        env:
        - name: TREE_ID
          valueFrom:
            configMapKeyRef:
              name: rekor-config
              key: treeID
        - name: SECRET_SIGNING_PWD
          valueFrom:
            secretKeyRef:
              name: rekor-signing-secret
              key: signing-secret-password
        volumeMounts:
        - name: rekor-secrets
          mountPath: "/var/run/rekor-secrets"
          readOnly: true
      volumes:
      - name: rekor-secrets
        secret:
          secretName: rekor-signing-secret
          items:
          - key: signing-secret
            path: signing-secret
