apiVersion: v1
kind: Secret
metadata:
  name: rekor-signing-secret
  namespace: rekor-system
type: Opaque
data:
  password: <password-placeholder>
  private: <private-placeholder>
  public: <public-placeholder>
---
apiVersion: v1
kind: Secret
metadata:
  name: rekor-pub-key
  namespace: rekor-system
type: Opaque
data:
  public: <public-placeholder>
