apiVersion: v1
kind: Secret
metadata:
  name: fulcio-secret
  namespace: fulcio-system
type: Opaque
data:
  password: <password-placeholder>
  private: <private-placeholder>
  cert: <cert-placeholder>
---
apiVersion: v1
kind: Secret
metadata:
  name: fulcio-pub-key
  namespace: fulcio-system
type: Opaque
data:
  cert: <cert-placeholder>
