---
apiVersion: v1
kind: Secret
metadata:
  name: ctlog-secret
  namespace: ctlog-system
type: Opaque
data:
  fulcio: <cert-placeholder>
  private: <private-placeholder>
---
apiVersion: v1
kind: Secret
metadata:
  name: ctlog-public-key
  namespace: ctlog-system
type: Opaque
data:
  public: <public-placeholder>
